# Cadastrar mulher
POST http://localhost:8080/api/mulher
Content-Type: application/json

{
    "nomeMulher" : "Julia Alves",
    "email" : "julia@gmail.com",
    "senha" : "senha123",
    "dtNascimento" : "01/01/2000",
    "cpf" : 123456,
    "cpfDigito" : 12,
    "telefone" : 123456789,
    "telefoneDDD" : 11
}

###

# Listar mulher
GET http://localhost:8080/api/mulher

###

# Listar mulher por id
GET http://localhost:8080/api/mulher/1

###

# Apagar mulher
DELETE http://localhost:8080/api/mulher/1
Authorization: Basic paula@gmail.com 123

###

# Atualizar mulher
PUT http://localhost:8080/api/mulher/1
Content-Type: application/json
Authorization: Basic paula@gmail.com 123

{
    "nomeMulher" : "Larissa Silva",
    "email" : "larissa@gmail.com",
    "senha" : "123",
    "dtNascimento" : "10/01/2000",
    "cpf" : 12345689,
    "cpfDigito" : 12,
    "telefone" : 123456789,
    "telefoneDDD" : 82
}

###

//cadastro localEscolhido
# Cadastrar
POST http://localhost:8080/api/localEscolhido
Content-Type: application/json

{
"codMulher" : 1,
    "incidente" : "tres caras numa moto",
    "dtOcorrencia" : "11/12/2022",
    "avaliacaoPerigo" : 5,
        "endereco" : {
        "numeroCep": 111222333,
        "nomeRua": "Bom retiro",
        "numeroRua": "25",
        "desComplemento": "Ao lado do shopping cidade sao paulo",
        "bairro" : {
            "nomeBairro" : "Paulista",
            "cidade" : {
                "nomeCidade" : "São Paulo",
                "siglaCidade" : "SP",
                "estado" : {
                    "nomeEstado" : "São paulo",
                    "siglaEstado" : "SP"
                }
            }
        }
    }
}

###

# Listar localEscolhido
GET http://localhost:8080/api/localEscolhido

###

# Listar localEscolhido
GET http://localhost:8080/api/localEscolhido/1

###

# Apagar localEscolhido
DELETE http://localhost:8080/api/localEscolhido/1
Content-Type: application/json
Authorization: Basic paula@gmail.com 123

###

# Atualizar localEscolhido
PUT http://localhost:8080/api/localEscolhido/1
Content-Type: application/json
Authorization: Basic paula@gmail.com 123

{
"codMulher" : 1,
    "incidente" : "dois caras numa moto",
    "dtOcorrencia" : "20/12/2022",
    "avaliacaoPerigo" : 5,
        "endereco" : {
        "numeroCep": 111222333,
        "nomeRua": "Avenida paulista",
        "numeroRua": "25",
        "desComplemento": "Ao lado do shopping cidade sao paulo",
        "bairro" : {
            "nomeBairro" : "Paulista",
            "cidade" : {
                "nomeCidade" : "São Paulo",
                "siglaCidade" : "SP",
                "estado" : {
                    "nomeEstado" : "São paulo",
                    "siglaEstado" : "SP"
                }
            }
        }
    }
}

###